# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/dhcpd

- name: Setup dhcpd
  ansible.builtin.template:
    src: dhcpd.conf
    dest: /etc/dhcp/
    mode: "+r"
    backup: true
  tags: dhcpd
# isc-dhcp-server
