scrape_configs:
  - job_name: job_name
    static_configs:
      - targets:
      {% for ip in prometheus_x %}
          - {{ ip }}:9100
      {% endfor %}

      # {% for ip in prometheus_x %}
      #     - {{ ip | ansible.utils.usable_range }}:9100
      # {% endfor %}
